language: python
python:
- '2.7'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3c7bb4ac01ca_key -iv $encrypted_3c7bb4ac01ca_iv
  -in travis_secrets.tar.enc -out travis_secrets.tar -d
- tar xvf travis_secrets.tar
- mv gce_travis /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/gce_travis
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/Infra-2ed7216cd032.json"
  global:
  - secure: giyoFa0wHdmTGCn1uTgpv2794spZj9l0igr52xNZZ6udLP9Z2wnH2WACPwrCXA5TfiyUQPnhlRkovhpWp7z7I9I5R5uEul1QKhaxZyRh4N/lCHI5QCuqNlR8dWuvcZJi0y8VDr2bLyWF4GkdKDEHvvueI8WWX8ZDuO5au4YzQPx0C2jVEE9aH1T0MbwcCD4NaRVCXUig21t9uEyuf2mC3T8CLEWf9gdGQJi+XNXevC+NofWiNdlmDZxnmnFP0WLdPDfg4ePJRC1P7wY9oT9XX+s4j4x2yIjoEDi9MiZUaK8EO1zeONrIbRlAze24TQhXDBeDO//c5Cfr5GxF52Ff/FbSd2C43JgClwbX/tvto0Vr8f4knAvi8cmq2nR1EfnixVpXxvMEraZIsG81pdxmwGENaWwJF0OWo9gxneayZbz9g8Xp4B9kti2Kkmc1yo2GZ4+vwZVpgN4Ao/w8euKH+OpdN+KOUQz94v+/aPVP2oILyBWtE6PUa3/lpo23vIVgzt4qEd1kg5fDfO0yeuZn4M7C4+9U+0Xc5EeUhakW4zEDcg/qflZx7VvL6JRdnyKPga9n9pm54wZ7YIlaaxicuVnuYswuPMeYOM5NfLdszE5puFE5W9wHC0KDDAKwQoRt768WmfOIz2n4v00H5cph1w0N16pVSlrz9OW9/jyy9cc=
  - secure: EvdRK/7hIutcEoDLkAG92DUSaoc9VONBD/WEOj6PyUB2bRnk5/4dK9YCK2dl5ETigL2c7J0oH+yo5k0okKOzyycAS2TM+1pII2S8EVX8PGBqubViSIlZgbBYDMEj9+PFeKowzzUpL+jUk2Sdwp5m7Xfik9+TxSau73UTQrIfV86auVnrJuAW2DhRq4GX7kBVq3WFw8aNWc2gxQZjxczBzI4jefknOX5wm650A/A6x3bzFTSK3Lc409mvZH3x60gGxt9wx5yuiclEimUQHppUnMkc4coTS8LIo+Kodsz3pBY1Rhc7Qa6HY+oQdP+NYm6a0yjuJKmROgx8C0YGLQyGgOA9XoPx9/YcVtM1S1AZHctEZ1BaK8oKsdXjShq096vbiVjJaZ+UcSFlZO/ynzzc7eEtU9e/XFQM1y9an6gccdUapFYjLnYikDlklWGlaFjpY52RHw79c7xpeILUC6LLRHbf2PhuFvUj8jXKjmhnmfsYaZMb7eAO8+FA0omzwmI+l+Z72tmYpl4cAqR93/6FUhyQmQP9fAmsmbfiiUdxRvUTUrXkkLUf4PLqujaTN6Cjpdr73iqagrIij3N4k+cKKyQBdBdlvfxQHkeTH1t/T1/w8w6cDk0DXBYYOEZGMjLdh4+/M3/6Yvq3amfk8qlCThfxRnKFwvYozm7okYeeDRU=
  - secure: fhJ6HNNB5sMzYiGj4l9AmpUAszSrIggxrbm0Qaco3C/P/765d9nXMizqjpR4XrPul26GS1AXj/mwb5OqmMyOdAUUfDgej9EkO35HUPHjnWvTfK8X0OJ2Bbc9ZcV0z2jBgCdOmZAeeWJEB5tA35zj9YJgoXC3Z5JTbdxWovwbh+BCqpHPACNd3YWdMZbimX77w8Zlr9jn6boPJ2wa7+sI7cw7D4uUhDI8MlbScQ5iEy1jllqMZ0qvTl93LfZmslFFRAbTjZvg/VNMpC5fvj0SGRU1LBJ1oHoROlzZNEx1QoPKR01V0wcI2C0kumtHiLRk7vpiazlofvS28YDo3E+++tx3QI093IdCirq1PGn+V9Yq8MGUk8qomAYgkvEV4uz5t/sp+GuN1PrpM3c7hM21n8CwkmdiTSOB0atIdDyKL2YYWbGDeDivwHhr0m6bhFZZQO+1JSydl4SN6NNrtswMsacQhR4OZcY/P+wU0eblQ8glAMgMv5YQjlkTc+sCOVk8zEyRRlLSEWsXT8vhvttPxoK2NvbZnv0FrL4zWA9oCsUb+EEEEnImcoM+C2vah3QZzaR/g9UTjmnpvpDkNXrRNksR4pzNzciBMnafG+tpBRnL9E9cM70DtGEZ6bYu/N5W2k+ixVEhKm4dDdadeu/ImXWUxvhYio2RbsUbsfBpcik=
